# Generated by Django 5.2.7 on 2025-11-08 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='BRAND_NAME', max_length=144)),
                ('desc', models.TextField(db_column='BRAND_DESC')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', db_default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', db_default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=144)),
                ('desc', models.TextField(db_column='DESCRIPTION')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', db_default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', db_default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='PRODUCTS', max_length=144)),
                ('description', models.TextField(db_column='DESCRIPTION')),
                ('price', models.IntegerField(db_column='PRICE', validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(db_column='COLOR', max_length=144)),
                ('product_image', models.ImageField(db_column='PRODUCT_IMAGES', help_text='Upload Images with name as "product_name.jpg" for corrent mapping with Products. Ex. "blue_shirt.jpg".', upload_to='media/products/')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', db_default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', db_default=False)),
                ('brand', models.ForeignKey(db_column='brand_fk', on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='shopping_data.brand')),
                ('category', models.ForeignKey(db_column='category_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_products', to='shopping_data.category')),
            ],
        ),
    ]
