# Generated by Django 5.2.7 on 2026-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_column='BRAND_NAME', max_length=144, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(db_column='PRODUCT_IMAGES', help_text='Upload Images with name as "product_name.jpg" for correct mapping with Products. Ex. "blue_shirt.jpg".', upload_to='media/products/'),
        ),
    ]
